### PR TITLE
Add OAP bootstrap

### PR DESCRIPTION
**Pull request by HongW2019**

### CODE REVIEW

**Comment by jerrychenhf** [comment]
Will there is a review meeting for this? As we previously communicated,  I will not do offline review for PR with more than 10 lines

**Comment by jerrychenhf** [comment]
Will you have a review meeting for this? Just as we communicated before, I will not do a full offline review for PRs with more than 10 code lines in change.

**Comment by HongW2019** [comment]
Yes, thanks for reminding,  the review meeting was sent out.

**Comment by HongW2019** [comment]
> Will you have a review meeting for this? Just as we communicated before, I will not do a full offline review for PRs with more than 10 code lines in change.

Yes, thanks for reminding,  the review meeting was sent out.

**Pull request merged**
