### PR TITLE
Support hdfs

### PR DESCRIPTION
**Pull request by haojinIntel**

### CODE REVIEW

**Review by jerrychenhf — COMMENTED** [review]
Thanks Jin Hao for come out the code so quickly.
There are many changes to the common part for Enable HDFS. Considering what we positioned HDFS functionality, we suggest to limit the changes in configuration.sh and services.sh so that we make it as simple and isolated as possible.

So what I suggest to do:

In configuration.sh:
similar in set_resources_for_spark: jq to get the spark runtime flag of enable_hdfs.
And do a configuration for HDFS if it is enabled.

In services.sh
jq to get the spark runtime flag of enable_hdfs.
if enabled, start the corresponding services. (do a format on head node if needed.)

**Comment by jerrychenhf** [comment]
@haojinIntel  considering the importance of workspace work and you are busy working on that, I will take your HDFS code as reference and I will commit the simplified HDFS code as above.

**Comment by haojinIntel** [comment]
@jerrychenhf 
```
if [ $ENABLE_HDFS == "true" ]; then
       # Format hdfs once
       ${HADOOP_HOME}/bin/hdfs namenode -format
fi

# Create event log dir on cloud storage if needed
# This needs to be done after hadoop file system has been configured correctly
${HADOOP_HOME}/bin/hadoop fs -mkdir -p /shared/spark-events
```
"${HADOOP_HOME}/bin/hadoop fs -mkdir -p /shared/spark-events" can only be executed after HDFS has been started. The code here is wrong.

**Comment by haojinIntel** [comment]
Have finished the function.

**Pull request closed without merging**
