### PR TITLE
Support modpython for ganglia on Ubuntu20.04

### PR DESCRIPTION
**Pull request by haojinIntel**

### CODE REVIEW

**Comment by jerrychenhf** [comment]
Thanks Jin Hao!
Overall it is good. While I have a little concern on install_ganglia_monitor_python.
How heavy this installation is?
My concern is, if this step needs to install a heavy (a lot of compile tools and dependencies") tool chain for compiling, it will make each CloudTik worker a dev environment other than runtime environment. (cluster node setting up took longer time and leave a lot of thing which will be used only once).

One possible approach to consider is: whether we can compile this offline as part of cloudtik compiling and upload the binary/package to s3 downloading through cloudfront.

In the future, we may have similar things such as the previous Fuse thing Yaoqing investigated. We would try best to avoid compiling at the runtime as the installation process for clearness and performance.

Thanks,
Haifeng

**Comment by jerrychenhf** [comment]
Thanks Jin Hao!
Overall it is good. While I have a little concern on install_ganglia_monitor_python.
How heavy this installation is?
My concern is, if this step needs to install a heavy (a lot of compile tools and dependencies") tool chain for compiling, it will make each CloudTik worker a dev environment other than runtime environment. (cluster node setting up took longer time and leave a lot of thing which will be used only once).

One possible approach to consider is: whether we can compile this offline as part of cloudtik compiling and upload the binary/package to s3 downloading through cloudfront.

In the future, we may have similar things such as the previous Fuse thing Yaoqing investigated. We would try best to avoid compiling at the runtime as the installation process for clearness and performance.

Thanks,
Haifeng

**Comment by jerrychenhf** [comment]
Additionally, please create a JIRA ticket in OAP -> cloudtik (component) to tracking this request.

**Comment by jerrychenhf** [comment]
Additionally, please create a JIRA ticket in OAP -> cloudtik (component) to tracking this request.

**Comment by haojinIntel** [comment]
@jerrychenhf Hi, haifeng. I've removed the code about compiling ganglia-monitor-core from install.sh to build.sh. Now we can easily support python module for ganglia by downloading the modpython.so from our repository. While I don't know how to upload the binary to this link``` https://d30257nes7d4fq.cloudfront.net/downloads/cloudtik/ganglia/modpython.so```,  so there are upload commands that need your help to improve.

**Comment by jerrychenhf** [comment]
@haojinIntel Thanks for the improvements!
I have uploaded modpython.so to s3://cloudtik/downloads/ganglia/

**Pull request merged**
