### PR TITLE
Deploy the documentation on Read the Docs and the docs outline

### PR DESCRIPTION
**Pull request by HongW2019**
This patch is to deploy documentation on Read the Docs and implement the docs outline at first. 
Here is the [demo](https://hongw2019-cloudtik.readthedocs.io/en/commit-rtd/index.html) for this PR.

### CODE REVIEW

**Comment by jerrychenhf** [comment]
You may already aware the below and have a plan there. Let me drop a note:
Please note that Getting Started has some similar contents for creating cluster, managing cluster. But that's a simple and beginner version.

The User Guide sections should have a more completed covering of these topics. It is not a simple repeat of moving the same contents from the starting guide to user guide sections.

**Comment by HongW2019** [comment]
Got it,  the corresponding guides to cover more complex topics will be submitted in the future PRs.

**Comment by jerrychenhf** [comment]
Additionally, please create a JIRA ticket in OAP -> cloudtik (component) to tracking this request.

**Comment by HongW2019** [comment]
> Additionally, please create a JIRA ticket in OAP -> cloudtik (component) to tracking this request.

Done.

**Pull request merged**
