### PR TITLE
Specify the version of docker

### PR DESCRIPTION
**Pull request by haojinIntel**

### CODE REVIEW

**Comment by haojinIntel** [comment]
@jerrychenhf The latest docker version was just released on 2/2/2023. We can use docker-20.10 to control the change.

image

**Review by jerrychenhf — COMMENTED** [review]
It's great that there is a simple way to control the VERSION. 
For robustness, how about retry without version if it failed (for example, in the future, the version is no longer available)

((export VERSION=20.10 && sudo bash /tmp/get-docker.sh > /dev/null) || sudo bash /tmp/get-docker.sh > /dev/null)

**Comment by haojinIntel** [comment]
@jerrychenhf Yes, I agree. I check the content of the script "/tmp/get-docker.sh" and found that it does not have the functionality to install the latest version if the specified version does not exist.

**Comment by jerrychenhf** [comment]
Thanks for the improvement. It's good for me.

**Pull request merged**
