### PR TITLE
Create tmp hadoop credential every time when configuring runtime.

### PR DESCRIPTION
**Pull request by yao531441**

### CODE REVIEW

**Comment by jerrychenhf** [comment]
@yao531441 I will made a few more changes and put this change together.

**Comment by jerrychenhf** [comment]
There is also another problem which will have problem on host mode or other cases.  
hadoop credential create some_key will fail if the key already exists. This will happen for host mode cases when the already been configured once and we run start cluster again to reconfigure the cluster.

**Comment by yao531441** [comment]
@jerrychenhf Please help to review and merge.

**Comment by jerrychenhf** [comment]
Thanks for the improvement!

**Pull request merged**
